In [6]:
%run  start.py

In [7]:
data_df = pd.read_csv('data/auto-mpg.csv')
data_df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,car_name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86,2790,15.6,82,1,ford mustang gl
394,44.0,4,97.0,52,2130,24.6,82,2,vw pickup
395,32.0,4,135.0,84,2295,11.6,82,1,dodge rampage
396,28.0,4,120.0,79,2625,18.6,82,1,ford ranger
397,31.0,4,119.0,82,2720,19.4,82,1,chevy s-10

In [8]:
data_df = data_df.drop(['car_name', 'origin', 'horsepower'], axis=1)
data_df

      mpg  cylinders  displacement  weight  acceleration  model_year
0    18.0          8         307.0    3504          12.0          70
1    15.0          8         350.0    3693          11.5          70
2    18.0          8         318.0    3436          11.0          70
3    16.0          8         304.0    3433          12.0          70
4    17.0          8         302.0    3449          10.5          70
..    ...        ...           ...     ...           ...         ...
393  27.0          4         140.0    2790          15.6          82
394  44.0          4          97.0    2130          24.6          82
395  32.0          4         135.0    2295          11.6          82
396  28.0          4         120.0    2625          18.6          82
397  31.0          4         119.0    2720          19.4          82

[398 rows x 6 columns]

In [9]:
y = data_df['mpg']     ## 종속변수
x = data_df.drop(['mpg'], axis=1, inplace=False)   # 독립변수들

In [10]:
from sklearn.model_selection import train_test_split

# 훈련용 데이터(70%)와 평가용 데이터(30%)로 분할
x_train, x_test, y_train, y_test = train_test_split(x, y,  test_size=0.3,  random_state=0)

In [11]:
x_train

     cylinders  displacement  weight  acceleration  model_year
230          8         350.0    4165          11.4          77
357          4         119.0    2615          14.8          81
140          8         304.0    4257          15.5          74
22           4         104.0    2375          17.5          70
250          8         318.0    3735          13.2          78
..         ...           ...     ...           ...         ...
323          4         156.0    2800          14.4          80
192          6         250.0    3353          14.5          76
117          4          68.0    1867          19.5          73
47           6         250.0    3282          15.0          71
172          4          90.0    2223          16.5          75

[278 rows x 5 columns]

In [12]:
from sklearn.linear_model import LinearRegression

# 모델생성
lr = LinearRegression()

# 모델 훈련
lr.fit(x_train, y_train)

# 선형회귀분석 : 평가 데이터에 대한 예측 수행 -> 예측 결과 y_predict 구하기
y_predict = lr.predict(x_test)
y_predict

array([12.68813886, 24.89235692, 11.77966226, 20.713484  , 17.59974974,
       28.70463932, 31.8246109 , 24.79459783, 13.3797074 , 28.03809202,
       33.95480562, 32.517138  , 21.28643713, 26.32547953, 16.29305741,
       32.16905355, 30.04731897, 29.90617451, 17.78110613, 30.69577551,
       15.33574367, 25.60299563, 25.4723533 , 20.04730443, 30.70244174,
       26.79576507, 32.20306918, 31.95533215, 30.42830733, 18.19432511,
       21.19981862, 29.62938625, 20.86352443, 30.82503708, 24.35511863,
       23.81034331, 21.45816755, 16.77101118, 31.95362794,  8.06590693,
        9.60178767, 13.8699291 , 27.26165312, 29.00102026, 29.52364892,
       22.58571769, 23.20233694, 13.80533693, 23.86039376, 28.12535283,
       31.40954528, 26.70297991, 15.34381889, 25.01897062, 14.71481708,
        9.53883961, 19.64272577, 26.82491432, 31.30917854, 14.99268593,
       20.64360774, 25.57610711, 22.45200894, 19.72033566, 10.7918702 ,
       11.42513414,  9.7023088 , 19.68724093, 24.98227534,  9.68717343,
       33.31781779, 10.21150582, 20.84069925, 19.27272978, 22.433523  ,
       29.31460799, 28.98886268, 28.57314167, 29.70646598, 16.24391797,
       12.49894224, 27.56814445, 31.316997  , 28.68118177, 29.66437625,
       32.04882992, 30.8361982 , 22.17956394, 25.77213654, 33.10831266,
       26.98725183,  9.31849574, 24.561598  , 30.46294223, 26.92507413,
       20.48685255, 21.39982273, 26.8941778 , 24.40347588, 11.0940889 ,
       24.94815562, 31.77003445, 26.34464772, 24.80388473, 34.16462001,
       28.28719769, 26.58609469, 15.23776302, 15.52356134, 22.23803733,
       21.89024654, 28.84734697, 17.53206177, 32.29959921, 24.10712862,
       25.46146791, 31.7308764 , 11.83478151, 17.74825111, 32.1876973 ])

In [13]:
from sklearn.metrics import r2_score

r2 = r2_score(y_test, y_predict)
print(r2)

0.8078579451877173

In [14]:
print("연비를 예측하고 싶은 차의 정보를 입력해주세요.")

cylinders_1 = int(input("cylinders : "))
displacement_1 = int(input("displacement : "))
weight_1 = int(input("weight : "))
acceleration_1 = int(input("acceleration : "))
model_year_1 = int(input("model_year : "))

mpg_predict = lr.predict([[cylinders_1, displacement_1, weight_1, acceleration_1 ,
                                                                       model_year_1]])

print("이 자동차의 예상 연비(mpg)는 %.2f 입니다." %mpg_predict)

연비를 예측하고 싶은 차의 정보를 입력해주세요.

cylinders :  6
displacement :  300
weight :  3200
acceleration :  11
model_year :  88

이 자동차의 예상 연비(mpg)는 30.71 입니다.